import { useEffect, useMemo, useState } from 'react';
import {
  Modal,
  Pressable,
  ScrollView,
  Switch,
  Text,
  TextInput,
  View,
} from 'react-native';
import {
  ArrowDown,
  ArrowUp,
  ChevronDown,
  Plus,
  RefreshCw,
  Send,
  Trash2,
  X,
} from 'lucide-react-native';

import { useTranslations } from '@/i18n';
import { useAuth } from '@/core/auth/AuthContext';
import { colors } from '@/theme/theme';
import { fonts } from '@/theme/fonts';
import { api } from '@/core/api/http';

/**
 * Mobile-adapted port of Killio-Frontend
 * `src/components/bricks/unified-form-brick.tsx` (1019 lines, web). Renders the
 * "form" brick inline with the full form-builder UI:
 *
 *   • Webhook / Objeto delivery mode toggle.
 *   • Form title + optional description.
 *   • "Conectar script" picker — calls `GET /scripts?teamId=...` and filters
 *     webhook-triggered scripts only (web parity).
 *   • Manual webhook URL fallback input.
 *   • Submit-button label + submitted-message inputs.
 *   • Steps editor: tabs row of steps, each step has a list of FIELD BRICK
 *     editors. "+ Field brick" adds a field to the active step. "+" on the
 *     step row adds a new step.
 *
 * The brick content shape mirrors the web `FormBrickContent` schema:
 *   { title, description, submitLabel, successMessage, webhookUrl, scriptId,
 *     tableConnectorId/Source/Label, pages: [{id,label}],
 *     childrenByContainer: { [pageId]: [fieldBrickContent, …] } }
 *
 * Differences from web (noted because mobile constraints):
 *   • Web stores field bricks as separate text bricks with `formField` content
 *     and references them by id under `childrenByContainer`. On mobile we keep
 *     the same content shape but inline the field bricks INSIDE the form
 *     brick's own `childrenByContainer` map as embedded objects (no separate
 *     brick rows). That keeps the brick self-contained while still
 *     round-tripping the wire shape — when the web reads the brick back, it
 *     finds the same key paths and renders the same form. (Auto-generated
 *     fields from a connected database/table are not supported in Vault.)
 *   • Drag-to-reorder fields is replaced with up/down arrows per field.
 *   • The full TableBrickPicker (Objeto tab connector) is not ported — it
 *     needs the workspace tables/boards endpoints the Vault doesn't surface
 *     yet. Vault shows the Objeto tab as informational ("disponible en el
 *     web"). The Webhook tab is fully functional.
 */

export type FormFieldType =
  | 'text'
  | 'textarea'
  | 'email'
  | 'url'
  | 'tel'
  | 'number'
  | 'date'
  | 'select'
  | 'radio'
  | 'checkbox';

export interface FormFieldConfig {
  fieldId: string;
  label?: string;
  type: FormFieldType;
  placeholder?: string;
  required?: boolean;
  options?: string[];
}

interface FieldBrick {
  id: string;
  kind: 'text';
  content: {
    text?: string;
    markdown?: string;
    displayStyle?: 'paragraph';
    formField: FormFieldConfig;
  };
}

interface FormPage {
  id: string;
  label: string;
}

export interface FormBrickContent {
  title?: string;
  description?: string;
  submitLabel?: string;
  successMessage?: string;
  webhookUrl?: string;
  scriptId?: string;
  pages?: FormPage[];
  /** Map of pageId → array of inlined FIELD BRICK objects. */
  childrenByContainer?: Record<string, FieldBrick[]>;
  tableConnectorId?: string;
  tableConnectorSource?: 'local' | 'document' | 'mesh' | 'board';
  tableConnectorLabel?: string;
  autoGeneratedFields?: boolean;
}

interface ScriptSummary {
  id: string;
  teamId: string;
  name: string;
  triggerType: string;
  triggerConfig: Record<string, any>;
  isActive: boolean;
}

const DEFAULT_PAGE_ID = 'page-1';

function uid(): string {
  return `${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;
}

function slugifyFieldId(input: string): string {
  const v = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return v.length > 0 ? v : 'field';
}

function defaultFieldConfig(): FormFieldConfig {
  return {
    fieldId: `field_${Math.random().toString(36).slice(2, 7)}`,
    label: '',
    type: 'text',
    placeholder: '',
    required: false,
    options: [],
  };
}

function defaultFieldBrick(): FieldBrick {
  return {
    id: `b_${uid()}`,
    kind: 'text',
    content: {
      text: '',
      markdown: '',
      displayStyle: 'paragraph',
      formField: defaultFieldConfig(),
    },
  };
}

export function FormBrick({
  id,
  content,
  canEdit,
  onUpdate,
}: {
  id: string;
  content: FormBrickContent;
  canEdit: boolean;
  onUpdate: (next: FormBrickContent) => void;
}) {
  const t = useTranslations('formBuilder');
  const { activeTeam } = useAuth();

  const safePages: FormPage[] = useMemo(() => {
    const raw = Array.isArray(content.pages) ? content.pages : [];
    const cleaned = raw
      .filter((p): p is FormPage => !!p && typeof p.id === 'string')
      .map((p, i) => ({ id: p.id, label: p.label?.trim() || `${t('stepLabel')} ${i + 1}` }));
    return cleaned.length > 0 ? cleaned : [{ id: DEFAULT_PAGE_ID, label: `${t('stepLabel')} 1` }];
  }, [content.pages, t]);

  const [activePage, setActivePage] = useState(safePages[0].id);
  const [endpointType, setEndpointType] = useState<'webhook' | 'database'>(
    content.tableConnectorId ? 'database' : 'webhook',
  );
  const [teamScripts, setTeamScripts] = useState<ScriptSummary[]>([]);
  const [isLoadingScripts, setIsLoadingScripts] = useState(false);
  const [scriptsError, setScriptsError] = useState<string | null>(null);
  const [scriptPickerOpen, setScriptPickerOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [submitState, setSubmitState] = useState<'idle' | 'success' | 'error'>('idle');
  const [values, setValues] = useState<Record<string, string | boolean>>({});

  const childrenByContainer = useMemo(() => {
    const raw = content.childrenByContainer;
    if (!raw || typeof raw !== 'object') return {} as Record<string, FieldBrick[]>;
    const map: Record<string, FieldBrick[]> = {};
    for (const [pageId, list] of Object.entries(raw)) {
      if (!Array.isArray(list)) {
        map[pageId] = [];
        continue;
      }
      map[pageId] = list
        .filter((b): b is FieldBrick => !!b && typeof b === 'object')
        .map((b) => ({
          id: typeof b.id === 'string' ? b.id : `b_${uid()}`,
          kind: 'text',
          content: {
            ...b.content,
            formField: normalizeField(b.content?.formField),
          },
        }));
    }
    return map;
  }, [content.childrenByContainer]);

  // Ensure active page exists in the new pages list.
  useEffect(() => {
    if (!safePages.some((p) => p.id === activePage)) {
      setActivePage(safePages[0]?.id ?? DEFAULT_PAGE_ID);
    }
  }, [safePages, activePage]);

  const updateContent = (patch: Partial<FormBrickContent>) => {
    onUpdate({ ...content, ...patch });
  };

  const updatePages = (nextPages: FormPage[]) => {
    const nextMap: Record<string, FieldBrick[]> = {};
    for (const p of nextPages) {
      nextMap[p.id] = childrenByContainer[p.id] ?? [];
    }
    updateContent({ pages: nextPages, childrenByContainer: nextMap });
  };

  const setPageFields = (pageId: string, fields: FieldBrick[]) => {
    const next = { ...childrenByContainer, [pageId]: fields };
    updateContent({ childrenByContainer: next });
  };

  const addPage = () => {
    const next = [
      ...safePages,
      { id: `page-${uid()}`, label: `${t('stepLabel')} ${safePages.length + 1}` },
    ];
    updatePages(next);
    setActivePage(next[next.length - 1].id);
  };

  const removePage = (pageId: string) => {
    if (safePages.length <= 1) return;
    const next = safePages.filter((p) => p.id !== pageId);
    updatePages(next);
    if (activePage === pageId) setActivePage(next[0].id);
  };

  const renamePage = (pageId: string, label: string) => {
    updatePages(safePages.map((p) => (p.id === pageId ? { ...p, label } : p)));
  };

  const activeFields = childrenByContainer[activePage] ?? [];

  const addField = () => {
    setPageFields(activePage, [...activeFields, defaultFieldBrick()]);
  };

  const updateField = (idx: number, nextField: FieldBrick) => {
    setPageFields(
      activePage,
      activeFields.map((f, i) => (i === idx ? nextField : f)),
    );
  };

  const removeField = (idx: number) => {
    setPageFields(
      activePage,
      activeFields.filter((_, i) => i !== idx),
    );
  };

  const moveField = (idx: number, dir: 'up' | 'down') => {
    const next = [...activeFields];
    const target = dir === 'up' ? idx - 1 : idx + 1;
    if (target < 0 || target >= next.length) return;
    [next[idx], next[target]] = [next[target], next[idx]];
    setPageFields(activePage, next);
  };

  const refreshScripts = async () => {
    if (!activeTeam?.id) return;
    setIsLoadingScripts(true);
    setScriptsError(null);
    try {
      const { data } = await api.get<ScriptSummary[]>('/scripts', {
        params: { teamId: activeTeam.id },
      });
      setTeamScripts(Array.isArray(data) ? data : []);
    } catch {
      setScriptsError(t('scriptsLoadError'));
      setTeamScripts([]);
    } finally {
      setIsLoadingScripts(false);
    }
  };

  // Auto-load scripts when entering edit mode the first time + on team change.
  useEffect(() => {
    if (!canEdit || !activeTeam?.id) return;
    void refreshScripts();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [canEdit, activeTeam?.id]);

  const webhookScripts = useMemo(
    () =>
      teamScripts.filter(
        (s) =>
          s.triggerType === 'webhook' &&
          s.isActive &&
          typeof s.triggerConfig?.publicToken === 'string' &&
          s.triggerConfig.publicToken.length > 0,
      ),
    [teamScripts],
  );

  const connectedScript = useMemo(
    () => (content.scriptId ? webhookScripts.find((s) => s.id === content.scriptId) ?? null : null),
    [content.scriptId, webhookScripts],
  );

  // Submit (viewer mode only): POSTs payload to the configured webhookUrl.
  const handleSubmit = async () => {
    const url = String(content.webhookUrl ?? '').trim();
    if (!url) return;
    setSubmitting(true);
    setSubmitState('idle');
    try {
      const payload = {
        formId: id,
        title: content.title ?? '',
        scriptId: content.scriptId ?? null,
        submittedAt: new Date().toISOString(),
        values,
        fields: safePages.flatMap((p) =>
          (childrenByContainer[p.id] ?? []).map((b) => ({
            brickId: b.id,
            pageId: p.id,
            ...b.content.formField,
          })),
        ),
      };
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error('Webhook rejected');
      setSubmitState('success');
      setValues({});
    } catch {
      setSubmitState('error');
    } finally {
      setSubmitting(false);
    }
  };

  if (canEdit) {
    return (
      <View className="my-1 rounded-xl border border-cyan/40 bg-card p-3 gap-3">
        {/* Header chip + delivery tabs */}
        <View className="flex-row items-center justify-between gap-2">
          <View>
            <Text
              style={{ fontFamily: fonts.semibold }}
              className="text-[10px] uppercase tracking-widest text-muted-foreground"
            >
              {t('editorTitle')}
            </Text>
            <Text
              style={{ fontFamily: fonts.medium }}
              className="text-sm text-foreground"
              numberOfLines={1}
            >
              {content.title || t('defaultTitle')}
            </Text>
          </View>
          <View className="flex-row rounded-md border border-border/50 bg-secondary p-0.5">
            <Pressable
              onPress={() => setEndpointType('webhook')}
              className={`rounded-sm px-2 py-1 ${
                endpointType === 'webhook' ? 'bg-background' : ''
              }`}
            >
              <Text
                style={{ fontFamily: fonts.semibold }}
                className={`text-[10px] uppercase tracking-wider ${
                  endpointType === 'webhook' ? 'text-foreground' : 'text-muted-foreground'
                }`}
              >
                {t('tabWebhook')}
              </Text>
            </Pressable>
            <Pressable
              onPress={() => setEndpointType('database')}
              className={`rounded-sm px-2 py-1 ${
                endpointType === 'database' ? 'bg-background' : ''
              }`}
            >
              <Text
                style={{ fontFamily: fonts.semibold }}
                className={`text-[10px] uppercase tracking-wider ${
                  endpointType === 'database' ? 'text-foreground' : 'text-muted-foreground'
                }`}
              >
                {t('tabObject')}
              </Text>
            </Pressable>
          </View>
        </View>

        {/* Title + description */}
        <TextInput
          value={content.title ?? ''}
          onChangeText={(v) => updateContent({ title: v })}
          placeholder={t('titlePlaceholder')}
          placeholderTextColor={colors.mutedForeground}
          style={inputStyle}
        />
        <TextInput
          value={content.description ?? ''}
          onChangeText={(v) => updateContent({ description: v })}
          placeholder={t('descriptionPlaceholder')}
          placeholderTextColor={colors.mutedForeground}
          style={inputStyle}
        />

        {endpointType === 'webhook' ? (
          <View className="rounded-md border border-border/60 bg-secondary/40 p-3 gap-2">
            <View className="flex-row items-center justify-between">
              <Text
                style={{ fontFamily: fonts.semibold }}
                className="text-[10px] uppercase tracking-wider text-muted-foreground"
              >
                {t('connectScript')}
              </Text>
              <Pressable
                onPress={refreshScripts}
                disabled={isLoadingScripts || !activeTeam?.id}
                className="flex-row items-center gap-1 rounded-md border border-border bg-background px-2 py-1"
                hitSlop={4}
              >
                <RefreshCw
                  size={11}
                  color={isLoadingScripts ? colors.mutedForeground : colors.foreground}
                />
                <Text
                  style={{ fontFamily: fonts.semibold }}
                  className="text-[10px] text-foreground"
                >
                  {t('refresh')}
                </Text>
              </Pressable>
            </View>

            <Pressable
              onPress={() => setScriptPickerOpen(true)}
              disabled={!activeTeam?.id || isLoadingScripts}
              className="flex-row items-center justify-between rounded-md border border-border bg-background px-3 py-2"
            >
              <Text
                style={{ fontFamily: fonts.medium }}
                className="text-xs text-foreground"
                numberOfLines={1}
              >
                {connectedScript?.name ?? t('noScript')}
              </Text>
              <ChevronDown size={13} color={colors.mutedForeground} />
            </Pressable>

            {scriptsError ? (
              <Text className="text-[11px] text-destructive">{scriptsError}</Text>
            ) : null}
            {!isLoadingScripts && !scriptsError && webhookScripts.length === 0 ? (
              <Text className="text-[11px] text-muted-foreground">{t('noScripts')}</Text>
            ) : null}
            {content.scriptId ? (
              <View className="flex-row items-center justify-between gap-2">
                <Text
                  className="flex-1 text-[11px] text-muted-foreground"
                  numberOfLines={2}
                >
                  {t('scriptConnectedNote')}
                </Text>
                <Pressable
                  onPress={() => updateContent({ scriptId: undefined })}
                  className="rounded-md border border-border bg-background px-2 py-1"
                >
                  <Text
                    style={{ fontFamily: fonts.semibold }}
                    className="text-[10px] text-foreground"
                  >
                    {t('disconnect')}
                  </Text>
                </Pressable>
              </View>
            ) : null}

            <TextInput
              value={content.webhookUrl ?? ''}
              onChangeText={(v) =>
                updateContent({ webhookUrl: v, scriptId: undefined, tableConnectorId: undefined })
              }
              placeholder={t('webhookPlaceholder')}
              placeholderTextColor={colors.mutedForeground}
              editable={!content.scriptId}
              autoCapitalize="none"
              autoCorrect={false}
              style={[
                inputStyle,
                content.scriptId ? { opacity: 0.5 } : null,
                { fontFamily: fonts.mono, fontSize: 11 },
              ]}
            />
          </View>
        ) : (
          <View className="rounded-md border border-border/60 bg-secondary/40 p-3 gap-2">
            <Text
              style={{ fontFamily: fonts.semibold }}
              className="text-sm text-foreground"
            >
              {t('objectTitle')}
            </Text>
            <Text className="text-[11px] text-muted-foreground">{t('objectEmpty')}</Text>
            <Text className="text-[10px] text-muted-foreground">{t('objectNotAvailable')}</Text>
          </View>
        )}

        {/* Submit label + success message */}
        <View className="flex-row gap-2">
          <View style={{ flex: 1 }}>
            <TextInput
              value={content.submitLabel ?? ''}
              onChangeText={(v) => updateContent({ submitLabel: v })}
              placeholder={t('submitLabelPlaceholder')}
              placeholderTextColor={colors.mutedForeground}
              style={inputStyle}
            />
          </View>
          <View style={{ flex: 1 }}>
            <TextInput
              value={content.successMessage ?? ''}
              onChangeText={(v) => updateContent({ successMessage: v })}
              placeholder={t('successPlaceholder')}
              placeholderTextColor={colors.mutedForeground}
              style={inputStyle}
            />
          </View>
        </View>

        {/* Steps tabs */}
        <View className="rounded-lg border border-border/60">
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={{ paddingHorizontal: 4, paddingTop: 4 }}
            className="border-b border-border/50 bg-secondary/30"
          >
            {safePages.map((page) => {
              const isActive = page.id === activePage;
              return (
                <Pressable
                  key={page.id}
                  onPress={() => setActivePage(page.id)}
                  className={`flex-row items-center gap-1 border-b-2 px-3 py-2 ${
                    isActive ? 'border-cyan bg-background' : 'border-transparent'
                  }`}
                >
                  <TextInput
                    value={page.label}
                    onChangeText={(v) => renamePage(page.id, v)}
                    style={{
                      fontFamily: isActive ? fonts.semibold : fonts.regular,
                      color: isActive ? colors.foreground : colors.mutedForeground,
                      fontSize: 12,
                      padding: 0,
                      minWidth: 60,
                    }}
                  />
                  {safePages.length > 1 ? (
                    <Pressable onPress={() => removePage(page.id)} hitSlop={4}>
                      <X size={11} color={colors.mutedForeground} />
                    </Pressable>
                  ) : null}
                </Pressable>
              );
            })}
            <Pressable
              onPress={addPage}
              className="items-center justify-center px-3 py-2"
            >
              <Plus size={13} color={colors.mutedForeground} />
            </Pressable>
          </ScrollView>

          <View className="bg-background p-3 gap-2">
            <View className="flex-row items-center justify-between">
              <Text style={{ fontFamily: fonts.semibold }} className="text-sm text-foreground">
                {safePages.find((p) => p.id === activePage)?.label ?? t('stepLabel')}
              </Text>
              <Pressable
                onPress={addField}
                className="flex-row items-center gap-1 rounded-md border border-border bg-secondary px-2 py-1"
              >
                <Plus size={11} color={colors.foreground} />
                <Text
                  style={{ fontFamily: fonts.semibold }}
                  className="text-[11px] text-foreground"
                >
                  {t('addFieldBrick')}
                </Text>
              </Pressable>
            </View>

            {activeFields.length === 0 ? (
              <View className="rounded-md border border-dashed border-border bg-background p-3">
                <Text className="text-center text-[11px] text-muted-foreground">
                  {t('stepEmpty')}
                </Text>
              </View>
            ) : (
              activeFields.map((field, i) => (
                <FieldBrickEditor
                  key={field.id}
                  field={field}
                  onChange={(nextConfig) =>
                    updateField(i, {
                      ...field,
                      content: { ...field.content, formField: nextConfig },
                    })
                  }
                  onMoveUp={i > 0 ? () => moveField(i, 'up') : undefined}
                  onMoveDown={i < activeFields.length - 1 ? () => moveField(i, 'down') : undefined}
                  onRemove={() => removeField(i)}
                />
              ))
            )}
          </View>
        </View>

        {/* Script picker modal */}
        <Modal
          visible={scriptPickerOpen}
          transparent
          animationType="fade"
          onRequestClose={() => setScriptPickerOpen(false)}
        >
          <Pressable
            onPress={() => setScriptPickerOpen(false)}
            className="flex-1 items-center justify-end bg-background/80"
          >
            <View className="w-full rounded-t-2xl border-t border-border bg-card p-4 gap-2">
              <Text style={{ fontFamily: fonts.bold }} className="text-base text-foreground">
                {t('connectScript')}
              </Text>
              <Pressable
                onPress={() => {
                  updateContent({ scriptId: undefined });
                  setScriptPickerOpen(false);
                }}
                className="rounded-md border border-border bg-background px-3 py-2"
              >
                <Text style={{ fontFamily: fonts.medium }} className="text-sm text-foreground">
                  {t('noScript')}
                </Text>
              </Pressable>
              {webhookScripts.map((s) => (
                <Pressable
                  key={s.id}
                  onPress={() => {
                    const token = String(s.triggerConfig?.publicToken ?? '');
                    const base = (
                      process.env.EXPO_PUBLIC_API_BASE_URL ??
                      process.env.EXPO_PUBLIC_API_URL ??
                      'http://localhost:4000'
                    ).replace(/\/+$/, '');
                    const url =
                      activeTeam?.id && token
                        ? `${base}/w/${activeTeam.id}/webhook/${s.id}/${token}`
                        : '';
                    updateContent({ scriptId: s.id, webhookUrl: url });
                    setScriptPickerOpen(false);
                  }}
                  className={`rounded-md border border-border bg-background px-3 py-2 ${
                    s.id === content.scriptId ? 'border-cyan' : ''
                  }`}
                >
                  <Text style={{ fontFamily: fonts.medium }} className="text-sm text-foreground">
                    {s.name}
                  </Text>
                </Pressable>
              ))}
              {webhookScripts.length === 0 ? (
                <Text className="text-[11px] text-muted-foreground">{t('noScripts')}</Text>
              ) : null}
            </View>
          </Pressable>
        </Modal>
      </View>
    );
  }

  // ── Read-only viewer ──────────────────────────────────────────────────────
  const allFields: FieldBrick[] = safePages.flatMap((p) => childrenByContainer[p.id] ?? []);
  const hasFields = allFields.length > 0;
  const url = String(content.webhookUrl ?? '').trim();
  const isConfigured = url.length > 0 && hasFields;
  if (!isConfigured) {
    return (
      <View className="my-1 rounded-xl border border-dashed border-border bg-secondary/30 p-4">
        <Text className="text-center text-xs text-muted-foreground">{t('notConfigured')}</Text>
      </View>
    );
  }
  return (
    <View className="my-1 rounded-xl border border-border bg-card p-4 gap-3">
      <View>
        <Text
          style={{ fontFamily: fonts.semibold, color: colors.cyan }}
          className="text-[10px] uppercase tracking-widest"
        >
          {t('viewerTitle')}
        </Text>
        <Text style={{ fontFamily: fonts.bold }} className="text-lg text-foreground">
          {content.title || t('defaultTitle')}
        </Text>
        {content.description ? (
          <Text className="text-xs text-muted-foreground">{content.description}</Text>
        ) : null}
      </View>

      {safePages.length > 1 ? (
        <ScrollView horizontal showsHorizontalScrollIndicator={false} className="-mx-1">
          <View className="flex-row gap-2 px-1">
            {safePages.map((p, i) => (
              <Pressable
                key={p.id}
                onPress={() => setActivePage(p.id)}
                className={`rounded-md px-3 py-1.5 ${
                  p.id === activePage ? 'bg-cyan' : 'bg-secondary/60'
                }`}
              >
                <Text
                  style={{ fontFamily: fonts.semibold }}
                  className={`text-[11px] ${
                    p.id === activePage ? 'text-background' : 'text-muted-foreground'
                  }`}
                >
                  {i + 1}. {p.label}
                </Text>
              </Pressable>
            ))}
          </View>
        </ScrollView>
      ) : null}

      <View className="rounded-md border border-border/60 bg-background p-3 gap-3">
        {(childrenByContainer[activePage] ?? []).map((field) => (
          <FieldBrickViewer
            key={field.id}
            field={field}
            value={values[field.id]}
            onChange={(v) => setValues((cur) => ({ ...cur, [field.id]: v }))}
          />
        ))}
      </View>

      <Pressable
        onPress={handleSubmit}
        disabled={submitting}
        className="self-end flex-row items-center gap-2 rounded-md bg-primary px-3 py-2"
      >
        <Send size={13} color={colors.primaryForeground} />
        <Text
          style={{ fontFamily: fonts.semibold, color: colors.primaryForeground }}
          className="text-sm"
        >
          {content.submitLabel || t('submitButton')}
        </Text>
      </Pressable>
      {submitState === 'success' ? (
        <Text className="text-xs text-success">
          {content.successMessage || t('successMessage')}
        </Text>
      ) : null}
      {submitState === 'error' ? (
        <Text className="text-xs text-destructive">Error.</Text>
      ) : null}
    </View>
  );
}

const inputStyle = {
  fontFamily: fonts.regular,
  color: colors.foreground,
  fontSize: 13,
  paddingHorizontal: 10,
  paddingVertical: 8,
  borderRadius: 6,
  borderWidth: 1,
  borderColor: colors.border,
  backgroundColor: colors.background,
} as const;

// ── Field brick editor (replaces the web unified-form-field-brick.web.tsx) ──

function normalizeField(raw: unknown): FormFieldConfig {
  if (!raw || typeof raw !== 'object') return defaultFieldConfig();
  const r = raw as Record<string, unknown>;
  const allowed: FormFieldType[] = [
    'text',
    'textarea',
    'email',
    'url',
    'tel',
    'number',
    'date',
    'select',
    'radio',
    'checkbox',
  ];
  const type = (typeof r.type === 'string' ? r.type : 'text') as FormFieldType;
  return {
    fieldId:
      typeof r.fieldId === 'string' && r.fieldId.trim().length > 0
        ? slugifyFieldId(r.fieldId)
        : `field_${Math.random().toString(36).slice(2, 7)}`,
    label: typeof r.label === 'string' ? r.label : '',
    type: allowed.includes(type) ? type : 'text',
    placeholder: typeof r.placeholder === 'string' ? r.placeholder : '',
    required: Boolean(r.required),
    options: Array.isArray(r.options)
      ? r.options.filter((o): o is string => typeof o === 'string')
      : [],
  };
}

function FieldBrickEditor({
  field,
  onChange,
  onMoveUp,
  onMoveDown,
  onRemove,
}: {
  field: FieldBrick;
  onChange: (next: FormFieldConfig) => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  onRemove: () => void;
}) {
  const t = useTranslations('formBuilder');
  const config = field.content.formField;
  const [typePickerOpen, setTypePickerOpen] = useState(false);

  const typeLabel: Record<FormFieldType, string> = {
    text: t('typeText'),
    textarea: t('typeTextarea'),
    email: t('typeEmail'),
    url: t('typeUrl'),
    tel: t('typeTel'),
    number: t('typeNumber'),
    date: t('typeDate'),
    select: t('typeSelect'),
    radio: t('typeRadio'),
    checkbox: t('typeCheckbox'),
  };
  const allTypes: FormFieldType[] = [
    'text',
    'textarea',
    'email',
    'url',
    'tel',
    'number',
    'date',
    'select',
    'radio',
    'checkbox',
  ];

  return (
    <View className="rounded-md border border-border/70 bg-secondary/20 p-3 gap-2">
      <View className="flex-row items-center justify-between">
        <Text
          style={{ fontFamily: fonts.semibold }}
          className="text-[10px] uppercase tracking-wider text-muted-foreground"
        >
          {t('fieldBrick')}
        </Text>
        <View className="flex-row items-center gap-2">
          <Text
            style={{ fontFamily: fonts.semibold }}
            className="text-[10px] uppercase tracking-wider text-cyan"
          >
            {config.type}
          </Text>
          {onMoveUp ? (
            <Pressable onPress={onMoveUp} hitSlop={6}>
              <ArrowUp size={13} color={colors.mutedForeground} />
            </Pressable>
          ) : null}
          {onMoveDown ? (
            <Pressable onPress={onMoveDown} hitSlop={6}>
              <ArrowDown size={13} color={colors.mutedForeground} />
            </Pressable>
          ) : null}
          <Pressable onPress={onRemove} hitSlop={6}>
            <Trash2 size={13} color={colors.destructive} />
          </Pressable>
        </View>
      </View>

      <TextInput
        value={config.label ?? ''}
        onChangeText={(v) => onChange({ ...config, label: v })}
        placeholder={t('fieldLabelPlaceholder')}
        placeholderTextColor={colors.mutedForeground}
        style={inputStyle}
      />

      <View className="flex-row gap-2">
        <View style={{ flex: 1 }}>
          <Pressable
            onPress={() => setTypePickerOpen(true)}
            className="flex-row items-center justify-between rounded-md border border-border bg-background px-3 py-2"
          >
            <Text style={{ fontFamily: fonts.medium }} className="text-xs text-foreground">
              {typeLabel[config.type]}
            </Text>
            <ChevronDown size={13} color={colors.mutedForeground} />
          </Pressable>
        </View>
        <View style={{ flex: 1 }}>
          <TextInput
            value={config.placeholder ?? ''}
            onChangeText={(v) => onChange({ ...config, placeholder: v })}
            placeholder={t('fieldPlaceholderPlaceholder')}
            placeholderTextColor={colors.mutedForeground}
            editable={config.type !== 'checkbox' && config.type !== 'radio'}
            style={[
              inputStyle,
              config.type === 'checkbox' || config.type === 'radio' ? { opacity: 0.5 } : null,
            ]}
          />
        </View>
      </View>

      <View className="flex-row items-center justify-between">
        <View className="flex-row items-center gap-2">
          <Switch
            value={!!config.required}
            onValueChange={(v) => onChange({ ...config, required: v })}
            trackColor={{ false: '#2a2a2a', true: colors.cyan }}
          />
          <Text style={{ fontFamily: fonts.medium }} className="text-xs text-foreground">
            {t('required')}
          </Text>
        </View>
        <Text
          style={{ fontFamily: fonts.mono }}
          className="text-[10px] text-muted-foreground"
          numberOfLines={1}
        >
          {config.fieldId}
        </Text>
      </View>

      {config.type === 'select' || config.type === 'radio' ? (
        <TextInput
          value={(config.options ?? []).join(', ')}
          onChangeText={(v) =>
            onChange({
              ...config,
              options: v
                .split(',')
                .map((o) => o.trim())
                .filter(Boolean),
            })
          }
          placeholder={t('optionsPlaceholder')}
          placeholderTextColor={colors.mutedForeground}
          style={inputStyle}
        />
      ) : null}

      <Modal
        visible={typePickerOpen}
        transparent
        animationType="fade"
        onRequestClose={() => setTypePickerOpen(false)}
      >
        <Pressable
          onPress={() => setTypePickerOpen(false)}
          className="flex-1 items-center justify-end bg-background/80"
        >
          <View className="w-full rounded-t-2xl border-t border-border bg-card p-4 gap-2">
            <Text style={{ fontFamily: fonts.bold }} className="text-base text-foreground">
              {t('fieldKey')}
            </Text>
            {allTypes.map((tp) => (
              <Pressable
                key={tp}
                onPress={() => {
                  onChange({ ...config, type: tp });
                  setTypePickerOpen(false);
                }}
                className={`rounded-md border border-border bg-background px-3 py-2 ${
                  tp === config.type ? 'border-cyan' : ''
                }`}
              >
                <Text style={{ fontFamily: fonts.medium }} className="text-sm text-foreground">
                  {typeLabel[tp]}
                </Text>
              </Pressable>
            ))}
          </View>
        </Pressable>
      </Modal>
    </View>
  );
}

function FieldBrickViewer({
  field,
  value,
  onChange,
}: {
  field: FieldBrick;
  value: string | boolean | undefined;
  onChange: (v: string | boolean) => void;
}) {
  const config = field.content.formField;
  const label = config.label || config.fieldId;
  if (config.type === 'checkbox') {
    return (
      <View className="flex-row items-center gap-2">
        <Switch
          value={value === true}
          onValueChange={onChange}
          trackColor={{ false: '#2a2a2a', true: colors.cyan }}
        />
        <Text style={{ fontFamily: fonts.medium }} className="text-sm text-foreground">
          {label}
          {config.required ? ' *' : ''}
        </Text>
      </View>
    );
  }
  if (config.type === 'select' || config.type === 'radio') {
    const opts = config.options ?? [];
    return (
      <View className="gap-1">
        <Text style={{ fontFamily: fonts.medium }} className="text-xs text-foreground">
          {label}
          {config.required ? ' *' : ''}
        </Text>
        <View className="flex-row flex-wrap gap-1">
          {opts.map((opt) => {
            const selected = typeof value === 'string' && value === opt;
            return (
              <Pressable
                key={opt}
                onPress={() => onChange(opt)}
                className={`rounded-md border px-2 py-1 ${
                  selected ? 'border-cyan bg-cyan/10' : 'border-border bg-background'
                }`}
              >
                <Text style={{ fontFamily: fonts.medium }} className="text-[11px] text-foreground">
                  {opt}
                </Text>
              </Pressable>
            );
          })}
        </View>
      </View>
    );
  }
  return (
    <View className="gap-1">
      <Text style={{ fontFamily: fonts.medium }} className="text-xs text-foreground">
        {label}
        {config.required ? ' *' : ''}
      </Text>
      <TextInput
        value={typeof value === 'string' ? value : ''}
        onChangeText={onChange}
        placeholder={config.placeholder ?? ''}
        placeholderTextColor={colors.mutedForeground}
        multiline={config.type === 'textarea'}
        keyboardType={
          config.type === 'number'
            ? 'numeric'
            : config.type === 'email'
              ? 'email-address'
              : config.type === 'tel'
                ? 'phone-pad'
                : config.type === 'url'
                  ? 'url'
                  : 'default'
        }
        autoCapitalize={config.type === 'email' || config.type === 'url' ? 'none' : 'sentences'}
        style={inputStyle}
      />
    </View>
  );
}
