/**
 * 1:1 mirror of Killio-Frontend src/lib/lucide-icon-registry.ts but using
 * `lucide-react-native` so inline `[lu:NAME:SW]` tokens render real Lucide
 * SVG icons in the Vault. Kebab-case keys + fallback aliases match the web
 * registry exactly; rebuilds across both apps stay in sync by keeping this
 * file's keys identical to the web one.
 */
import {
  AlertTriangle, AlignLeft, ArrowDown, ArrowLeft, ArrowRight, ArrowUp,
  AtSign, Award, BarChart2, BarChart3, Battery, Bell, BellOff, Bike, Book,
  BookOpen, Bookmark, Box, Boxes, Briefcase, Bug, Building2, Calendar, Camera,
  Car, Check, CheckCircle2, CheckSquare, ChevronDown, ChevronLeft, ChevronRight,
  ChevronUp, Circle, Clipboard, Clock, Cloud, CloudDownload, CloudUpload, Code,
  Coffee, Cog, Compass, Copy, CreditCard, Crown, Database, Diamond, DollarSign,
  Download, Edit, Edit2, Edit3, Eye, EyeOff, File, FileText, Files,
  Filter, Flag, Flame, FolderClosed, FolderOpen, Gauge, Gift, GitBranch,
  Globe, GraduationCap, Grid3x3, HandCoins, HardDrive, Headphones,
  Heart, HelpCircle, Home, Image as ImageIcon, Info, Key, Keyboard, Languages,
  Laptop, Layers, Layout, Leaf, Library, LifeBuoy, Lightbulb, Link2, List,
  ListChecks, Lock, LogIn, LogOut, Mail, Map, MapPin, Maximize2, Megaphone,
  Menu, MessageCircle, MessageSquare, Mic, Minus, Monitor, Moon, MoreHorizontal,
  Mountain, Music, Navigation, Newspaper, Package, Palette, Paperclip, Pause,
  Pen, Pencil, Phone, PieChart, Pin, Plane, Play, Plug, Plus, Power, Printer,
  Puzzle, QrCode, Quote, Radio, RefreshCw, Rocket, Rss, Save, Scale,
  Scissors, Search, Send, Server, Settings, Share2, Shield, ShieldCheck,
  ShoppingBag, ShoppingCart, Shovel, Sigma, Signal, Slash, Smartphone,
  Smile, Snowflake, Speaker, Sparkles, Star, Sticker, StickyNote, Sun,
  Table, Tag, Target, Terminal, ThumbsDown, ThumbsUp, Ticket, Timer, Trash2,
  TreePine, TrendingUp, Trophy, Truck, Tv, Type, Umbrella, Unlock,
  Upload, User, UserCheck, UserPlus, Users, Utensils, Video, Volume2, Wallet,
  Wand2, Warehouse, Watch, Waves, Wifi, Wind, Wrench, X, XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';

export const LUCIDE_REGISTRY: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle, 'align-left': AlignLeft,
  'arrow-down': ArrowDown, 'arrow-left': ArrowLeft, 'arrow-right': ArrowRight, 'arrow-up': ArrowUp,
  'at-sign': AtSign, award: Award,
  'bar-chart': BarChart2, 'bar-chart-2': BarChart2, 'bar-chart-3': BarChart3,
  battery: Battery, bell: Bell, 'bell-off': BellOff, bike: Bike,
  book: Book, 'book-open': BookOpen, bookmark: Bookmark, box: Box, boxes: Boxes,
  briefcase: Briefcase, bug: Bug, building: Building2, 'building-2': Building2,
  calendar: Calendar, camera: Camera, car: Car, check: Check, 'check-circle': CheckCircle2,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown, 'chevron-left': ChevronLeft, 'chevron-right': ChevronRight, 'chevron-up': ChevronUp,
  circle: Circle, clipboard: Clipboard, clock: Clock,
  cloud: Cloud, 'cloud-download': CloudDownload, 'cloud-upload': CloudUpload,
  code: Code, coffee: Coffee, cog: Cog, gear: Cog, settings: Settings, compass: Compass,
  copy: Copy, 'credit-card': CreditCard, crown: Crown,
  database: Database, desktop: Monitor, diamond: Diamond, 'dollar-sign': DollarSign, dollar: DollarSign,
  download: Download, edit: Edit, 'edit-2': Edit2, 'edit-3': Edit3, pencil: Pencil, pen: Pen,
  envelope: Mail, mail: Mail, eye: Eye, 'eye-off': EyeOff,
  file: File, 'file-text': FileText, files: Files, filter: Filter,
  flag: Flag, flame: Flame, fire: Flame,
  folder: FolderClosed, 'folder-open': FolderOpen, 'folder-closed': FolderClosed,
  gauge: Gauge, gift: Gift, 'git-branch': GitBranch,
  globe: Globe, 'graduation-cap': GraduationCap, grid: Grid3x3, 'grid-3x3': Grid3x3,
  'hand-coins': HandCoins, money: HandCoins,
  'hard-drive': HardDrive, headphones: Headphones, heart: Heart, 'help-circle': HelpCircle, question: HelpCircle,
  home: Home, house: Home, image: ImageIcon, info: Info, 'info-circle': Info,
  key: Key, keyboard: Keyboard, languages: Languages, laptop: Laptop, layers: Layers, layout: Layout,
  leaf: Leaf, library: Library, 'life-buoy': LifeBuoy, lightbulb: Lightbulb, idea: Lightbulb,
  link: Link2, 'link-2': Link2, list: List, 'list-checks': ListChecks, tasks: ListChecks,
  lock: Lock, 'log-in': LogIn, login: LogIn, 'log-out': LogOut, logout: LogOut,
  map: Map, 'map-pin': MapPin, 'map-marker': MapPin,
  maximize: Maximize2, 'maximize-2': Maximize2, megaphone: Megaphone, menu: Menu,
  message: MessageCircle, 'message-circle': MessageCircle, 'message-square': MessageSquare, comment: MessageCircle,
  mic: Mic, microphone: Mic, minus: Minus, monitor: Monitor, server: Server,
  moon: Moon, 'more-horizontal': MoreHorizontal, more: MoreHorizontal, mountain: Mountain,
  music: Music, navigation: Navigation, newspaper: Newspaper,
  package: Package, palette: Palette, 'paint-brush': Palette, paperclip: Paperclip, pause: Pause,
  phone: Phone, 'pie-chart': PieChart, pin: Pin, plane: Plane, play: Play, plug: Plug,
  plus: Plus, power: Power, printer: Printer, print: Printer, puzzle: Puzzle, 'qr-code': QrCode, quote: Quote,
  radio: Radio, refresh: RefreshCw, 'refresh-cw': RefreshCw, rocket: Rocket, rss: Rss,
  save: Save, scale: Scale, scissors: Scissors,
  search: Search, magnify: Search, 'magnifying-glass': Search,
  send: Send, 'paper-plane': Send, settings2: Settings,
  share: Share2, 'share-2': Share2, shield: Shield, 'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag, 'shopping-cart': ShoppingCart, cart: ShoppingCart,
  shovel: Shovel, sigma: Sigma, signal: Signal, slash: Slash,
  smartphone: Smartphone, mobile: Smartphone, smile: Smile, snowflake: Snowflake,
  speaker: Speaker, sparkles: Sparkles, magic: Sparkles, 'magic-wand': Wand2, wand: Wand2, 'wand-2': Wand2,
  star: Star, sticker: Sticker, 'sticky-note': StickyNote, note: StickyNote, sun: Sun,
  table: Table, tag: Tag, target: Target, terminal: Terminal,
  'thumbs-down': ThumbsDown, 'thumbs-up': ThumbsUp, ticket: Ticket, timer: Timer, hourglass: Timer,
  trash: Trash2, 'trash-2': Trash2,
  tree: TreePine, 'tree-pine': TreePine,
  'trending-up': TrendingUp, trophy: Trophy, truck: Truck, tv: Tv, type: Type,
  umbrella: Umbrella, unlock: Unlock, upload: Upload,
  user: User, 'user-check': UserCheck, 'user-plus': UserPlus, users: Users, person: User,
  utensils: Utensils, food: Utensils, video: Video, film: Video,
  'volume-2': Volume2, volume: Volume2,
  wallet: Wallet, warehouse: Warehouse, watch: Watch, waves: Waves,
  wifi: Wifi, wind: Wind, wrench: Wrench, tools: Wrench, hammer: Wrench,
  x: X, times: X, xmark: X, 'x-circle': XCircle, zap: Zap, bolt: Zap, lightning: Zap,
};

/** Lookup by lowercase kebab name; returns null if unknown. */
export function resolveLucide(name: string): LucideIcon | null {
  return LUCIDE_REGISTRY[name.toLowerCase()] ?? null;
}
