import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import {
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Loader2,
  Plus,
  Send,
  Trash2,
} from 'lucide-react-native';

import { useTranslations } from '@/i18n';
import { useAuth } from '@/core/auth/AuthContext';
import { listScripts, type ScriptSummary } from '@/core/api/scripts.client';
import { colors } from '@/theme/theme';
import { fonts } from '@/theme/fonts';
import {
  UnifiedFormFieldBrick,
  createDefaultFormFieldConfig,
  FormFieldRuntimeProvider,
  type FormFieldType,
  normalizeFormFieldConfig,
} from './unified-form-field-brick';

/**
 * React Native port of the web `unified-form-brick.tsx`.
 *
 * The brick API and content schema match the web file 1:1 — same prop names,
 * same content keys, same i18n namespace (`document-detail`) and same field
 * type names — so a brick authored on web round-trips through Vault and back
 * without any data conversion.
 *
 * Web → Native swap notes (key deltas from the source file):
 *   • Web uses `UnifiedBrickList` to render the form's child bricks (each
 *     field is a separate "text" brick with a `formField` content blob).
 *     RN ports the field brick component (`UnifiedFormFieldBrick`) but does
 *     NOT port the full unified brick list (it depends on @dnd-kit/* which
 *     isn't available). Instead we resolve the active page's bricks from
 *     `childrenByContainer` against `activeBricks` and render them inline
 *     with up/down arrow reorder.
 *     // TODO: long-press DnD via react-native-gesture-handler — phase 2
 *   • TableBrickPicker, `generateFormFieldsFromColumns`, and
 *     `generateCardFormFields` are not ported. The "Objeto" tab stays
 *     informational ("disponible en el web"). The webhook flow is fully
 *     functional. // Mobile: object connector requires the workspace
 *     boards/tables endpoints which Vault doesn't surface yet.
 *   • `useSession()` → `useAuth()`; `useParams()` → `useLocalSearchParams()`.
 *   • `listScripts(teamId, accessToken)` → vault scripts.client
 *     (`accessToken` arg is ignored — Vault's axios interceptor injects the
 *     bearer token; we keep the signature for source-parity).
 *   • `toast(msg, kind)` → `Alert.alert(...)` for errors, console.log for
 *     successes.
 *   • framer-motion → dropped (no animations needed for the form brick).
 *   • CSS classes that NativeWind doesn't understand (`hover:*`,
 *     `group/...`, `cursor-*`, `focus:ring-*`) are removed.
 */

type FormPage = {
  id: string;
  label: string;
};

type FormBrickContent = {
  title?: string;
  description?: string;
  submitLabel?: string;
  webhookUrl?: string;
  scriptId?: string;
  successMessage?: string;
  pages?: FormPage[];
  childrenByContainer?: Record<string, string[]>;
  fields?: any[]; // Deprecated, use field bricks instead
  // Database connector — kept in the schema; on RN we only display the label.
  tableConnectorId?: string;
  tableConnectorSource?: 'local' | 'document' | 'mesh' | 'board';
  tableConnectorLabel?: string;
  tableConnectorDocId?: string;
  autoGeneratedFields?: boolean;
};

interface UnifiedFormBrickProps {
  id: string;
  content: FormBrickContent;
  canEdit: boolean;
  onUpdate: (content: FormBrickContent) => void;
  activeBricks?: any[];
  onAddBrick?: (
    kind: string,
    afterBrickId?: string,
    parentProps?: { parentId: string; containerId: string },
    initialContent?: any,
  ) => void;
  onDeleteBrick?: (id: string) => void;
  onUpdateBrick?: (id: string, content: any) => void;
  onReorderBricks?: (ids: string[]) => void;
  onCrossContainerDrop?: (
    activeId: string,
    overId: string,
    options?: { intent?: 'move' | 'merge-text'; sourceContainerToken?: string; targetContainerToken?: string },
  ) => void;
  documents?: any[];
  boards?: any[];
  users?: any[];
}

const DEFAULT_PAGE_ID = 'page-1';
const DEFAULT_PAGE_LABEL = 'Paso 1';

const createPage = (index: number): FormPage => ({
  id: `page-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  label: `Paso ${index}`,
});

const isRequiredFieldMissing = (
  type: FormFieldType,
  required: boolean | undefined,
  value: string | boolean | undefined,
) => {
  if (!required) return false;
  if (type === 'checkbox') return value !== true;
  return typeof value !== 'string' || value.trim().length === 0;
};

const normalizeConditionText = (value: string | boolean | undefined): string => {
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'string') return value.trim().toLowerCase();
  return '';
};

const evaluateFieldCondition = (
  condition:
    | {
        enabled?: boolean;
        sourceFieldId?: string;
        operator?: string;
        value?: string;
      }
    | undefined,
  sourceValue: string | boolean | undefined,
): boolean => {
  if (!condition?.enabled) return true;
  const sourceFieldId = String(condition.sourceFieldId || '').trim();
  if (sourceFieldId.length === 0) return true;

  const operator = String(condition.operator || 'equals');
  const current = normalizeConditionText(sourceValue);
  const expected = normalizeConditionText(condition.value || '');

  if (operator === 'equals') return current === expected;
  if (operator === 'not_equals') return current !== expected;
  if (operator === 'contains') return current.includes(expected);
  if (operator === 'not_contains') return !current.includes(expected);
  if (operator === 'is_empty') return current.length === 0;
  if (operator === 'is_not_empty') return current.length > 0;
  if (operator === 'is_true') return current === 'true' || current === '1' || current === 'si' || current === 'yes';
  if (operator === 'is_false') return current === 'false' || current === '0' || current === 'no';

  return true;
};

// Lightweight stand-in for `resolveNestedBricks`. Walks the `childrenByContainer`
// id list for a given container and resolves each id against the document's
// activeBricks list — preserves the order the user arranged them in.
function resolveContainerBricks(
  childrenByContainer: Record<string, string[]>,
  containerId: string,
  activeBricks: any[],
): any[] {
  const ids = Array.isArray(childrenByContainer?.[containerId]) ? childrenByContainer[containerId] : [];
  if (ids.length === 0) return [];
  const byId = new Map<string, any>();
  for (const b of activeBricks || []) {
    if (b && typeof b.id === 'string') byId.set(b.id, b);
  }
  const out: any[] = [];
  for (const id of ids) {
    const brick = byId.get(id);
    if (brick) out.push(brick);
  }
  return out;
}

// Toast replacement: errors use Alert.alert (modal), info goes to the console.
// Mobile: the web `toast()` helper has no RN equivalent — we keep destructive
// signaling but drop the auto-dismiss snackbar.
const notify = (message: string, kind: 'success' | 'error' = 'success') => {
  if (kind === 'error') Alert.alert('', message);
  else console.log('[form-brick]', message);
};

export function UnifiedFormBrick({
  id,
  content,
  canEdit,
  onUpdate,
  activeBricks = [],
  onAddBrick,
  onDeleteBrick,
  onUpdateBrick,
  onReorderBricks,
  onCrossContainerDrop,
  documents,
  boards,
  users,
}: UnifiedFormBrickProps) {
  // Reference unused-but-prop-signature args so TypeScript doesn't whine.
  void onCrossContainerDrop;
  void documents;
  void boards;
  void users;
  void onReorderBricks;

  const t = useTranslations('document-detail');
  const { activeTeam } = useAuth();
  const activeTeamId = activeTeam?.id;
  // accessToken is injected by the axios interceptor; kept as a stub so
  // refresh/load gating reads exactly like the web code.
  const accessToken = activeTeamId ? 'managed-by-axios' : null;

  const params = useLocalSearchParams();
  const currentDocId = (params?.docId || params?.id) as string;
  // currentMeshId kept to mirror the web file shape (unused without a mesh route).
  const currentMeshId = (params?.meshId as string) || '';
  void currentMeshId;
  void currentDocId;

  const safePages = useMemo(() => {
    const pages = Array.isArray(content.pages)
      ? content.pages
          .filter((page): page is FormPage => Boolean(page && typeof page.id === 'string' && page.id.length > 0))
          .map((page, index) => ({
            id: page.id,
            label:
              typeof page.label === 'string' && page.label.trim().length > 0
                ? page.label
                : `Paso ${index + 1}`,
          }))
      : [];

    if (pages.length > 0) return pages;
    return [{ id: DEFAULT_PAGE_ID, label: DEFAULT_PAGE_LABEL }];
  }, [content.pages]);

  const [activePage, setActivePage] = useState(safePages[0]?.id || DEFAULT_PAGE_ID);
  const [values, setValues] = useState<Record<string, string | boolean>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitState, setSubmitState] = useState<'idle' | 'success' | 'error'>('idle');
  const [teamScripts, setTeamScripts] = useState<ScriptSummary[]>([]);
  const [isLoadingScripts, setIsLoadingScripts] = useState(false);
  const [scriptsLoadError, setScriptsLoadError] = useState<string | null>(null);
  const [endpointType, setEndpointType] = useState<'webhook' | 'database'>(
    content.tableConnectorId ? 'database' : 'webhook',
  );
  const [scriptPickerOpen, setScriptPickerOpen] = useState(false);

  const childrenByContainer = useMemo(() => {
    const raw = content.childrenByContainer;
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return {} as Record<string, string[]>;
    return raw as Record<string, string[]>;
  }, [content.childrenByContainer]);

  const pageBricksById = useMemo(() => {
    const map: Record<string, any[]> = {};
    for (const page of safePages) {
      map[page.id] = resolveContainerBricks(childrenByContainer, page.id, activeBricks);
    }
    return map;
  }, [safePages, childrenByContainer, activeBricks]);

  const pseudoFieldEntries = useMemo(() => {
    const entries: Array<{ brickId: string; pageId: string; config: ReturnType<typeof createDefaultFormFieldConfig> }> = [];
    for (const page of safePages) {
      const pageBricks = pageBricksById[page.id] || [];
      for (const brick of pageBricks) {
        const config = normalizeFormFieldConfig(brick?.content?.formField);
        if (!config) continue;
        entries.push({ brickId: brick.id, pageId: page.id, config });
      }
    }
    return entries;
  }, [safePages, pageBricksById]);

  const fieldIdToBrickId = useMemo(() => {
    const mapping: Record<string, string> = {};
    for (const entry of pseudoFieldEntries) {
      const fieldId = entry.config.fieldId;
      if (!fieldId || mapping[fieldId]) continue;
      mapping[fieldId] = entry.brickId;
    }
    return mapping;
  }, [pseudoFieldEntries]);

  const visiblePseudoFieldEntries = useMemo(() => {
    return pseudoFieldEntries.filter((entry) => {
      const condition = entry.config.condition;
      if (!condition?.enabled) return true;

      const sourceBrickId = fieldIdToBrickId[condition.sourceFieldId];
      const sourceValue = sourceBrickId ? values[sourceBrickId] : undefined;
      return evaluateFieldCondition(condition, sourceValue);
    });
  }, [pseudoFieldEntries, fieldIdToBrickId, values]);

  const visiblePseudoFieldIds = useMemo(() => {
    return new Set(visiblePseudoFieldEntries.map((entry) => entry.brickId));
  }, [visiblePseudoFieldEntries]);

  const hasPseudoFields = pseudoFieldEntries.length > 0;

  const viewerPageBricksById = useMemo(() => {
    const map: Record<string, any[]> = {};
    for (const page of safePages) {
      const pageBricks = pageBricksById[page.id] || [];
      map[page.id] = pageBricks.filter((brick) => {
        const config = normalizeFormFieldConfig(brick?.content?.formField);
        if (!config) return true;
        return visiblePseudoFieldIds.has(brick.id);
      });
    }
    return map;
  }, [safePages, pageBricksById, visiblePseudoFieldIds]);

  const navigablePages = useMemo(() => {
    if (canEdit || !hasPseudoFields) return safePages;
    const filtered = safePages.filter((page) => {
      const bricks = viewerPageBricksById[page.id] || [];
      return bricks.length > 0;
    });
    return filtered.length > 0 ? filtered : [safePages[0]];
  }, [canEdit, hasPseudoFields, safePages, viewerPageBricksById]);

  const activePageBricks = (canEdit ? pageBricksById[activePage] : viewerPageBricksById[activePage]) || [];

  const webhookBase = useMemo(
    () =>
      (
        process.env.EXPO_PUBLIC_API_BASE_URL ??
        process.env.EXPO_PUBLIC_KILLIO_API_URL ??
        process.env.EXPO_PUBLIC_API_URL ??
        'http://localhost:4000'
      ).replace(/\/+$/, ''),
    [],
  );

  const webhookScripts = useMemo(() => {
    return teamScripts.filter((script) => {
      const publicToken = script.triggerConfig?.publicToken;
      return (
        script.triggerType === 'webhook' &&
        script.isActive &&
        typeof publicToken === 'string' &&
        publicToken.length > 0
      );
    });
  }, [teamScripts]);

  const endpoint = String(content.webhookUrl ?? '').trim();
  const submitLabel = (content.submitLabel || t('form.submitButton') || 'Enviar').trim();
  const successMessage = (content.successMessage || t('form.successMessage') || 'Enviado correctamente.').trim();

  const isConfigured = endpoint.length > 0 && hasPseudoFields;

  useEffect(() => {
    if (navigablePages.some((page) => page.id === activePage)) return;
    setActivePage(navigablePages[0]?.id || DEFAULT_PAGE_ID);
  }, [navigablePages, activePage]);

  const updateContent = useCallback(
    (patch: Partial<FormBrickContent>) => {
      onUpdate({ ...content, ...patch });
    },
    [content, onUpdate],
  );

  const updatePages = (nextPages: FormPage[]) => {
    const nextChildrenByContainer: Record<string, string[]> = {};
    for (const page of nextPages) {
      nextChildrenByContainer[page.id] = Array.isArray(childrenByContainer[page.id])
        ? childrenByContainer[page.id]
        : [];
    }

    updateContent({
      pages: nextPages,
      childrenByContainer: nextChildrenByContainer,
    });
  };

  const addPage = () => {
    const nextPage = createPage(safePages.length + 1);
    const nextPages = [...safePages, nextPage];
    updatePages(nextPages);
    setActivePage(nextPage.id);
  };

  const removePage = (pageId: string) => {
    if (safePages.length <= 1) return;
    const nextPages = safePages.filter((page) => page.id !== pageId);
    updatePages(nextPages);
    if (activePage === pageId) {
      setActivePage(nextPages[0].id);
    }
  };

  const renamePage = (pageId: string, label: string) => {
    updatePages(safePages.map((page) => (page.id === pageId ? { ...page, label } : page)));
  };

  const addFieldBrick = () => {
    if (!canEdit || !onAddBrick) return;

    const afterBrickId = activePageBricks.length > 0 ? activePageBricks[activePageBricks.length - 1].id : undefined;
    onAddBrick(
      'text',
      afterBrickId,
      { parentId: id, containerId: activePage },
      {
        text: '',
        markdown: '',
        displayStyle: 'paragraph',
        formField: createDefaultFormFieldConfig(),
      },
    );
  };

  // Up/down arrow reorder — replaces the web @dnd-kit sortable.
  // TODO: long-press DnD via react-native-gesture-handler — phase 2
  const moveFieldBrick = (brickId: string, dir: 'up' | 'down') => {
    const ids = (childrenByContainer[activePage] || []).slice();
    const idx = ids.indexOf(brickId);
    if (idx < 0) return;
    const target = dir === 'up' ? idx - 1 : idx + 1;
    if (target < 0 || target >= ids.length) return;
    [ids[idx], ids[target]] = [ids[target], ids[idx]];
    updateContent({ childrenByContainer: { ...childrenByContainer, [activePage]: ids } });
  };

  const getWebhookUrlForScript = useCallback(
    (script: ScriptSummary): string | null => {
      const publicToken = script.triggerConfig?.publicToken;
      if (!activeTeamId || typeof publicToken !== 'string' || publicToken.length === 0) {
        return null;
      }
      return `${webhookBase}/w/${activeTeamId}/webhook/${script.id}/${publicToken}`;
    },
    [activeTeamId, webhookBase],
  );

  const refreshScripts = async () => {
    if (!activeTeamId || !accessToken) return;
    setIsLoadingScripts(true);
    setScriptsLoadError(null);
    try {
      const scripts = await listScripts(activeTeamId, accessToken);
      setTeamScripts(scripts);
    } catch (error) {
      console.error('Failed to load webhook scripts for form brick', error);
      setScriptsLoadError('No se pudieron cargar los scripts.');
    } finally {
      setIsLoadingScripts(false);
    }
  };

  const handleScriptSelection = (scriptId: string) => {
    if (!scriptId) {
      updateContent({ scriptId: undefined });
      return;
    }

    const script = webhookScripts.find((item) => item.id === scriptId);
    if (!script) {
      notify(t('form.invalidScript'), 'error');
      return;
    }

    const webhookUrl = getWebhookUrlForScript(script);
    if (!webhookUrl) {
      notify(t('form.webhookUrlError'), 'error');
      return;
    }

    updateContent({
      scriptId: script.id,
      webhookUrl,
      tableConnectorId: undefined,
      tableConnectorSource: undefined,
      tableConnectorDocId: undefined,
      tableConnectorLabel: undefined,
      autoGeneratedFields: undefined,
    });
  };

  useEffect(() => {
    if (!canEdit || !activeTeamId || !accessToken) return;

    let cancelled = false;
    const loadScripts = async () => {
      setIsLoadingScripts(true);
      setScriptsLoadError(null);
      try {
        const scripts = await listScripts(activeTeamId, accessToken);
        if (cancelled) return;
        setTeamScripts(scripts);
      } catch (error) {
        if (cancelled) return;
        console.error('Failed to load webhook scripts for form brick', error);
        setScriptsLoadError('No se pudieron cargar los scripts.');
      } finally {
        if (!cancelled) setIsLoadingScripts(false);
      }
    };

    void loadScripts();
    return () => {
      cancelled = true;
    };
  }, [canEdit, activeTeamId, accessToken]);

  useEffect(() => {
    if (!canEdit || !content.scriptId) return;
    const selectedScript = webhookScripts.find((script) => script.id === content.scriptId);
    if (!selectedScript) return;

    const webhookUrl = getWebhookUrlForScript(selectedScript);
    if (!webhookUrl) return;

    if (webhookUrl !== (content.webhookUrl ?? '')) {
      updateContent({ scriptId: selectedScript.id, webhookUrl });
    }
  }, [canEdit, content.scriptId, content.webhookUrl, webhookScripts, getWebhookUrlForScript, updateContent]);

  const setFieldValue = (brickId: string, value: string | boolean) => {
    setValues((current) => ({ ...current, [brickId]: value }));
  };

  const activePageIndex = navigablePages.findIndex((page) => page.id === activePage);
  const isLastPage = activePageIndex >= navigablePages.length - 1;

  const goToNextPage = () => {
    if (activePageIndex < 0 || isLastPage) return;

    const currentRequiredMissing = visiblePseudoFieldEntries.find((entry) => {
      return entry.pageId === activePage && isRequiredFieldMissing(entry.config.type, entry.config.required, values[entry.brickId]);
    });

    if (currentRequiredMissing) {
      notify(t('form.requiredFieldsStep'), 'error');
      return;
    }

    setActivePage(navigablePages[activePageIndex + 1].id);
  };

  const goToPreviousPage = () => {
    if (activePageIndex <= 0) return;
    setActivePage(safePages[activePageIndex - 1].id);
  };

  const handleSubmit = async () => {
    if (hasPseudoFields && !isLastPage) {
      goToNextPage();
      return;
    }

    if (!isConfigured) {
      notify(t('form.missingEndpoint') || 'Configura la URL del webhook antes de enviar.', 'error');
      return;
    }

    if (hasPseudoFields) {
      const missingEntry = visiblePseudoFieldEntries.find((entry) => {
        return isRequiredFieldMissing(entry.config.type, entry.config.required, values[entry.brickId]);
      });

      if (missingEntry) {
        setActivePage(missingEntry.pageId);
        notify(t('form.requiredFieldsSubmit'), 'error');
        return;
      }
    }

    setIsSubmitting(true);
    setSubmitState('idle');
    try {
      const normalizedValues = visiblePseudoFieldEntries.reduce<Record<string, string | boolean>>(
        (acc, entry) => {
          const value = values[entry.brickId];
          if (typeof value === 'undefined') return acc;
          const key = entry.config.fieldId || entry.brickId;
          acc[key] = value;
          return acc;
        },
        {},
      );

      const payload = {
        formId: id,
        title: content.title || '',
        scriptId: content.scriptId || null,
        submittedAt: new Date().toISOString(),
        values: normalizedValues,
        fields: visiblePseudoFieldEntries.map((entry) => ({
          brickId: entry.brickId,
          pageId: entry.pageId,
          ...entry.config,
        })),
      };

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        throw new Error('Webhook rejected the submission.');
      }

      setSubmitState('success');
      notify(successMessage, 'success');
      setValues({});
      setActivePage(navigablePages[0]?.id || DEFAULT_PAGE_ID);
      // Mobile: web uses setTimeout to clear the success banner. We keep the
      // banner visible until the user dismisses it with "Enviar otra".
    } catch (error) {
      console.error('Failed to submit form brick', error);
      setSubmitState('error');
      notify(t('form.submitError') || 'No se pudo enviar el formulario.', 'error');
    } finally {
      setIsSubmitting(false);
    }
  };

  const previewLabel = useMemo(() => {
    return content.title || t('form.defaultTitle') || 'Formulario';
  }, [content.title, t]);

  // ── Editor (canEdit=true) ─────────────────────────────────────────────────
  if (canEdit) {
    const connectedScript = content.scriptId
      ? webhookScripts.find((s) => s.id === content.scriptId)
      : null;

    return (
      <View className="rounded-xl border border-border bg-card p-4 shadow-sm gap-4">
        <View className="gap-2">
          <View className="flex-row items-center justify-between gap-3">
            <View style={{ flex: 1 }}>
              <Text
                style={{ fontFamily: fonts.semibold }}
                className="text-[10px] uppercase tracking-widest text-muted-foreground"
              >
                {t('form.editorTitle') || 'Formulario'}
              </Text>
              <Text style={{ fontFamily: fonts.medium }} className="text-sm text-foreground">
                {previewLabel}
              </Text>
            </View>
            <View className="flex-row rounded-md border border-border/50 bg-muted/40 p-0.5">
              <Pressable
                onPress={() => setEndpointType('webhook')}
                className={`rounded-sm px-2 py-1 ${endpointType === 'webhook' ? 'bg-background' : ''}`}
              >
                <Text
                  style={{ fontFamily: fonts.semibold }}
                  className={`text-[10px] uppercase tracking-wider ${
                    endpointType === 'webhook' ? 'text-foreground' : 'text-muted-foreground'
                  }`}
                >
                  Webhook
                </Text>
              </Pressable>
              <Pressable
                onPress={() => setEndpointType('database')}
                className={`rounded-sm px-2 py-1 ${endpointType === 'database' ? 'bg-background' : ''}`}
              >
                <Text
                  style={{ fontFamily: fonts.semibold }}
                  className={`text-[10px] uppercase tracking-wider ${
                    endpointType === 'database' ? 'text-foreground' : 'text-muted-foreground'
                  }`}
                >
                  Objeto
                </Text>
              </Pressable>
            </View>
          </View>

          <TextInput
            value={content.title || ''}
            onChangeText={(v) => updateContent({ title: v })}
            placeholder={t('form.titlePlaceholder') || 'Titulo del formulario'}
            placeholderTextColor={colors.mutedForeground}
            style={editorInputStyle}
          />
          <TextInput
            value={content.description || ''}
            onChangeText={(v) => updateContent({ description: v })}
            placeholder={t('form.descriptionPlaceholder') || 'Descripcion opcional'}
            placeholderTextColor={colors.mutedForeground}
            style={editorInputStyle}
          />

          {endpointType === 'webhook' ? (
            <>
              <View className="rounded-md border border-border/60 bg-muted/20 p-3 gap-2">
                <View className="flex-row items-center justify-between gap-2">
                  <Text
                    style={{ fontFamily: fonts.semibold }}
                    className="text-[10px] uppercase tracking-wider text-muted-foreground"
                  >
                    Conectar script
                  </Text>
                  <Pressable
                    onPress={refreshScripts}
                    disabled={isLoadingScripts || !activeTeamId || !accessToken}
                    className="rounded-md border border-border bg-background px-2 py-1"
                  >
                    {isLoadingScripts ? (
                      <Loader2 size={12} color={colors.mutedForeground} />
                    ) : (
                      <Text
                        style={{ fontFamily: fonts.semibold }}
                        className="text-[10px] text-foreground"
                      >
                        Refrescar
                      </Text>
                    )}
                  </Pressable>
                </View>

                {/* Mobile: web <select> → tappable row + bottom-sheet picker. */}
                <Pressable
                  onPress={() => setScriptPickerOpen(true)}
                  disabled={!activeTeamId || !accessToken || isLoadingScripts}
                  className="flex-row items-center justify-between rounded-md border border-border bg-background px-3 py-2"
                >
                  <Text
                    style={{ fontFamily: fonts.medium }}
                    className="text-xs text-foreground"
                    numberOfLines={1}
                  >
                    {connectedScript?.name ?? 'Ninguno (usar URL manual)'}
                  </Text>
                  <ChevronDown size={13} color={colors.mutedForeground} />
                </Pressable>

                {scriptsLoadError ? (
                  <Text className="text-xs text-destructive">{scriptsLoadError}</Text>
                ) : null}
                {!isLoadingScripts && webhookScripts.length === 0 ? (
                  <Text className="text-xs text-muted-foreground">
                    No hay scripts webhook activos en este workspace.
                  </Text>
                ) : null}
                {content.scriptId ? (
                  <View className="flex-row items-center justify-between gap-2">
                    <Text className="flex-1 text-xs text-muted-foreground">
                      Webhook conectado automaticamente desde el script seleccionado.
                    </Text>
                    <Pressable
                      onPress={() => updateContent({ scriptId: undefined })}
                      className="rounded-md border border-border bg-background px-2 py-1"
                    >
                      <Text
                        style={{ fontFamily: fonts.semibold }}
                        className="text-[10px] text-foreground"
                      >
                        Desconectar
                      </Text>
                    </Pressable>
                  </View>
                ) : null}
              </View>

              <TextInput
                value={content.webhookUrl || ''}
                onChangeText={(v) =>
                  updateContent({ webhookUrl: v, scriptId: undefined, tableConnectorId: undefined })
                }
                placeholder={t('form.webhookPlaceholder') || 'URL del webhook publico'}
                placeholderTextColor={colors.mutedForeground}
                editable={!content.scriptId}
                autoCapitalize="none"
                autoCorrect={false}
                style={[
                  editorInputStyle,
                  content.scriptId ? { opacity: 0.5 } : null,
                  { fontFamily: fonts.mono, fontSize: 11 },
                ]}
              />
            </>
          ) : (
            <View className="rounded-md border border-border/60 bg-muted/20 p-4 gap-3">
              <View className="flex-row items-center justify-between gap-2">
                <Text style={{ fontFamily: fonts.semibold }} className="text-sm text-foreground">
                  Conectar a Objeto
                </Text>
                {/* Mobile: TableBrickPicker not ported. Object connector is read-only on RN. */}
              </View>

              {content.tableConnectorId ? (
                <View className="rounded border border-primary/20 bg-primary/5 p-3 gap-2">
                  <View className="flex-row items-center justify-between">
                    <Text
                      style={{ fontFamily: fonts.medium }}
                      className="text-sm text-primary"
                    >
                      {content.tableConnectorLabel || 'Tabla seleccionada'}
                    </Text>
                    <Pressable
                      onPress={() =>
                        updateContent({
                          tableConnectorId: undefined,
                          tableConnectorLabel: undefined,
                          webhookUrl: undefined,
                        })
                      }
                      className="rounded-md border border-destructive/40 bg-background px-2 py-1"
                    >
                      <Text
                        style={{ fontFamily: fonts.semibold }}
                        className="text-[10px] text-destructive"
                      >
                        Desconectar
                      </Text>
                    </Pressable>
                  </View>
                  {content.autoGeneratedFields ? (
                    <Text className="text-xs text-muted-foreground">
                      Las preguntas del formulario se han generado automaticamente usando las
                      columnas de la tabla.
                    </Text>
                  ) : null}
                  {content.webhookUrl ? (
                    <Text className="text-[10px] text-muted-foreground">{content.webhookUrl}</Text>
                  ) : null}
                </View>
              ) : (
                <Text className="text-center text-sm text-muted-foreground">
                  Selector de objeto disponible en el web. Conecta el formulario a una tabla
                  desde el editor web; los datos guardados se sincronizan aqui.
                </Text>
              )}
            </View>
          )}

          <View className="flex-row gap-2">
            <View style={{ flex: 1 }}>
              <TextInput
                value={content.submitLabel || ''}
                onChangeText={(v) => updateContent({ submitLabel: v })}
                placeholder={t('form.submitLabelPlaceholder') || 'Etiqueta del boton'}
                placeholderTextColor={colors.mutedForeground}
                style={editorInputStyle}
              />
            </View>
            <View style={{ flex: 1 }}>
              <TextInput
                value={content.successMessage || ''}
                onChangeText={(v) => updateContent({ successMessage: v })}
                placeholder={t('form.successPlaceholder') || 'Mensaje al enviar'}
                placeholderTextColor={colors.mutedForeground}
                style={editorInputStyle}
              />
            </View>
          </View>
        </View>

        {/* Step tabs */}
        <View className="rounded-lg border border-border/60">
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            contentContainerStyle={{ paddingHorizontal: 4, paddingTop: 4 }}
            className="border-b border-border/50 bg-muted/20"
          >
            {safePages.map((page) => {
              const isActive = page.id === activePage;
              return (
                <Pressable
                  key={page.id}
                  onPress={() => setActivePage(page.id)}
                  className={`flex-row items-center gap-1 border-b-2 px-3 py-2 ${
                    isActive ? 'border-primary bg-background' : 'border-transparent'
                  }`}
                >
                  {/* Mobile: web shows tab-rename inline. We keep that — tap to focus,
                      then edit. The TextInput is wrapped in the same Pressable so a
                      tap inside the input doesn't reactivate the parent. */}
                  <TextInput
                    value={page.label}
                    onChangeText={(v) => renamePage(page.id, v)}
                    onFocus={() => setActivePage(page.id)}
                    style={{
                      fontFamily: isActive ? fonts.semibold : fonts.regular,
                      color: isActive ? colors.foreground : colors.mutedForeground,
                      fontSize: 13,
                      padding: 0,
                      minWidth: 70,
                    }}
                  />
                  {safePages.length > 1 ? (
                    <Pressable onPress={() => removePage(page.id)} hitSlop={6}>
                      <Trash2 size={12} color={colors.mutedForeground} />
                    </Pressable>
                  ) : null}
                </Pressable>
              );
            })}
            <Pressable onPress={addPage} className="items-center justify-center px-3 py-2">
              <Plus size={14} color={colors.mutedForeground} />
            </Pressable>
          </ScrollView>

          <View className="bg-background p-3 gap-3">
            <View className="flex-row items-center justify-between gap-2">
              <Text style={{ fontFamily: fonts.semibold }} className="text-sm text-foreground">
                {safePages.find((page) => page.id === activePage)?.label || 'Paso'}
              </Text>
              <Pressable
                onPress={addFieldBrick}
                className="flex-row items-center gap-2 rounded-md border border-border bg-secondary px-2 py-1"
              >
                <Plus size={12} color={colors.foreground} />
                <Text style={{ fontFamily: fonts.semibold }} className="text-[11px] text-foreground">
                  Field brick
                </Text>
              </Pressable>
            </View>

            {activePageBricks.length === 0 ? (
              <View className="rounded-md border border-dashed border-border bg-background p-3">
                <Text className="text-center text-xs text-muted-foreground">
                  Paso vacio. Agrega un field brick o cualquier bloque.
                </Text>
              </View>
            ) : (
              activePageBricks.map((brick, i) => (
                <FieldBrickRow
                  key={brick.id}
                  brick={brick}
                  canMoveUp={i > 0}
                  canMoveDown={i < activePageBricks.length - 1}
                  onMoveUp={() => moveFieldBrick(brick.id, 'up')}
                  onMoveDown={() => moveFieldBrick(brick.id, 'down')}
                  onDelete={() => onDeleteBrick?.(brick.id)}
                  onUpdate={(nextContent) => onUpdateBrick?.(brick.id, nextContent)}
                />
              ))
            )}
          </View>
        </View>

        {/* Script picker modal */}
        <Modal
          visible={scriptPickerOpen}
          transparent
          animationType="fade"
          onRequestClose={() => setScriptPickerOpen(false)}
        >
          <Pressable
            onPress={() => setScriptPickerOpen(false)}
            className="flex-1 items-center justify-end bg-background/80"
          >
            <View className="w-full rounded-t-2xl border-t border-border bg-card p-4 gap-2">
              <Text style={{ fontFamily: fonts.bold }} className="text-base text-foreground">
                Conectar script
              </Text>
              <Pressable
                onPress={() => {
                  handleScriptSelection('');
                  setScriptPickerOpen(false);
                }}
                className="rounded-md border border-border bg-background px-3 py-2"
              >
                <Text style={{ fontFamily: fonts.medium }} className="text-sm text-foreground">
                  Ninguno (usar URL manual)
                </Text>
              </Pressable>
              {webhookScripts.map((script) => (
                <Pressable
                  key={script.id}
                  onPress={() => {
                    handleScriptSelection(script.id);
                    setScriptPickerOpen(false);
                  }}
                  className={`rounded-md border border-border bg-background px-3 py-2 ${
                    script.id === content.scriptId ? 'border-primary' : ''
                  }`}
                >
                  <Text style={{ fontFamily: fonts.medium }} className="text-sm text-foreground">
                    {script.name}
                  </Text>
                </Pressable>
              ))}
              {webhookScripts.length === 0 ? (
                <Text className="text-xs text-muted-foreground">
                  No hay scripts webhook activos en este workspace.
                </Text>
              ) : null}
            </View>
          </Pressable>
        </Modal>
      </View>
    );
  }

  if (!isConfigured) {
    return (
      <View className="rounded-xl border border-dashed border-border bg-muted/20 p-6">
        <Text className="text-center text-sm text-muted-foreground">
          {t('form.notConfigured') || 'Este formulario todavia no esta configurado.'}
        </Text>
      </View>
    );
  }

  // ── Viewer (read-only / interactive) ──────────────────────────────────────
  return (
    <View className="rounded-xl border border-border bg-card p-5 gap-5">
      <View className="gap-1.5">
        <Text
          style={{ fontFamily: fonts.semibold, color: colors.cyan }}
          className="text-[10px] uppercase tracking-widest"
        >
          {t('form.viewerTitle') || 'Formulario'}
        </Text>
        <Text style={{ fontFamily: fonts.bold }} className="text-xl text-foreground">
          {content.title || t('form.defaultTitle') || 'Formulario'}
        </Text>
        {content.description ? (
          <Text className="text-sm text-muted-foreground">{content.description}</Text>
        ) : null}
      </View>

      <FormFieldRuntimeProvider
        value={{
          interactive: true,
          values,
          setValue: setFieldValue,
        }}
      >
        <View className="gap-4">
          {navigablePages.length > 1 ? (
            <ScrollView horizontal showsHorizontalScrollIndicator={false}>
              <View className="flex-row gap-2">
                {navigablePages.map((page, index) => (
                  <Pressable
                    key={page.id}
                    onPress={() => setActivePage(page.id)}
                    className={`rounded-md px-3 py-1.5 ${
                      activePage === page.id ? 'bg-cyan' : 'bg-muted/40'
                    }`}
                  >
                    <Text
                      style={{ fontFamily: fonts.semibold }}
                      className={`text-xs ${
                        activePage === page.id ? 'text-background' : 'text-muted-foreground'
                      }`}
                    >
                      {index + 1}. {page.label}
                    </Text>
                  </Pressable>
                ))}
              </View>
            </ScrollView>
          ) : null}

          <View className="rounded-lg border border-border/60 bg-background p-3 gap-3">
            {activePageBricks.length === 0 ? (
              <Text className="text-center text-xs text-muted-foreground">Paso sin contenido</Text>
            ) : (
              activePageBricks.map((brick) => {
                const config = normalizeFormFieldConfig(brick?.content?.formField);
                if (!config) {
                  // Non-field brick inside the page (free-form text, etc.). We render
                  // its plain text fallback — full inline brick rendering would
                  // require BrickRenderer, which creates a circular import here.
                  const text = String(brick?.content?.text ?? brick?.content?.markdown ?? '');
                  if (!text) return null;
                  return (
                    <Text key={brick.id} className="text-sm text-foreground">
                      {text}
                    </Text>
                  );
                }
                const label = config.label || config.fieldId;
                return (
                  <View key={brick.id} className="gap-1">
                    {config.type !== 'checkbox' ? (
                      <Text style={{ fontFamily: fonts.medium }} className="text-xs text-foreground">
                        {label}
                        {config.required ? ' *' : ''}
                      </Text>
                    ) : null}
                    {config.type === 'checkbox' ? (
                      <View className="flex-row items-center gap-2">
                        <UnifiedFormFieldBrick
                          id={brick.id}
                          config={config}
                          readonly={true}
                          onUpdate={() => undefined}
                          runtimeValue={values[brick.id]}
                          onRuntimeValueChange={(v) => setFieldValue(brick.id, v)}
                          interactive={true}
                        />
                        <Text className="text-sm text-foreground">
                          {label}
                          {config.required ? ' *' : ''}
                        </Text>
                      </View>
                    ) : (
                      <UnifiedFormFieldBrick
                        id={brick.id}
                        config={config}
                        readonly={true}
                        onUpdate={() => undefined}
                        runtimeValue={values[brick.id]}
                        onRuntimeValueChange={(v) => setFieldValue(brick.id, v)}
                        interactive={true}
                      />
                    )}
                  </View>
                );
              })
            )}
          </View>

          {navigablePages.length > 1 ? (
            <View className="flex-row items-center justify-between gap-2">
              <Pressable
                onPress={goToPreviousPage}
                disabled={activePageIndex <= 0}
                className={`flex-row items-center gap-2 rounded-md border border-border bg-background px-3 py-2 ${
                  activePageIndex <= 0 ? 'opacity-50' : ''
                }`}
              >
                <ChevronLeft size={14} color={colors.foreground} />
                <Text style={{ fontFamily: fonts.semibold }} className="text-sm text-foreground">
                  Anterior
                </Text>
              </Pressable>
              {!isLastPage ? (
                <Pressable
                  onPress={goToNextPage}
                  className="flex-row items-center gap-2 rounded-md bg-primary px-3 py-2"
                >
                  <Text
                    style={{ fontFamily: fonts.semibold, color: colors.primaryForeground }}
                    className="text-sm"
                  >
                    Siguiente
                  </Text>
                  <ChevronRight size={14} color={colors.primaryForeground} />
                </Pressable>
              ) : (
                <Pressable
                  onPress={handleSubmit}
                  disabled={isSubmitting}
                  className={`flex-row items-center gap-2 rounded-md bg-primary px-3 py-2 ${
                    isSubmitting ? 'opacity-60' : ''
                  }`}
                >
                  {isSubmitting ? (
                    <Loader2 size={14} color={colors.primaryForeground} />
                  ) : (
                    <Send size={14} color={colors.primaryForeground} />
                  )}
                  <Text
                    style={{ fontFamily: fonts.semibold, color: colors.primaryForeground }}
                    className="text-sm"
                  >
                    {submitLabel}
                  </Text>
                </Pressable>
              )}
            </View>
          ) : (
            <View className="flex-row justify-end">
              <Pressable
                onPress={handleSubmit}
                disabled={isSubmitting}
                className={`flex-row items-center gap-2 rounded-md bg-primary px-3 py-2 ${
                  isSubmitting ? 'opacity-60' : ''
                }`}
              >
                {isSubmitting ? (
                  <Loader2 size={14} color={colors.primaryForeground} />
                ) : (
                  <Send size={14} color={colors.primaryForeground} />
                )}
                <Text
                  style={{ fontFamily: fonts.semibold, color: colors.primaryForeground }}
                  className="text-sm"
                >
                  {submitLabel}
                </Text>
              </Pressable>
            </View>
          )}
        </View>
      </FormFieldRuntimeProvider>

      {submitState === 'success' ? (
        <View className="flex-row items-center justify-between gap-3 rounded-md border border-success/30 bg-success/10 p-3">
          <Text style={{ fontFamily: fonts.medium }} className="flex-1 text-sm text-success">
            {successMessage}
          </Text>
          <Pressable onPress={() => setSubmitState('idle')}>
            <Text style={{ fontFamily: fonts.semibold }} className="text-xs text-success">
              Enviar otra
            </Text>
          </Pressable>
        </View>
      ) : null}
      {submitState === 'error' ? (
        <View className="rounded-md border border-destructive/30 bg-destructive/10 p-3">
          <Text style={{ fontFamily: fonts.medium }} className="text-sm text-destructive">
            {t('form.submitError') || 'No se pudo enviar el formulario.'}
          </Text>
        </View>
      ) : null}
    </View>
  );
}

const editorInputStyle = {
  fontFamily: fonts.regular,
  color: colors.foreground,
  fontSize: 13,
  paddingHorizontal: 10,
  paddingVertical: 8,
  borderRadius: 6,
  borderWidth: 1,
  borderColor: colors.border,
  backgroundColor: colors.background,
} as const;

// ── Editor row for a single field brick ──────────────────────────────────────

function FieldBrickRow({
  brick,
  canMoveUp,
  canMoveDown,
  onMoveUp,
  onMoveDown,
  onDelete,
  onUpdate,
}: {
  brick: any;
  canMoveUp: boolean;
  canMoveDown: boolean;
  onMoveUp: () => void;
  onMoveDown: () => void;
  onDelete: () => void;
  onUpdate: (nextContent: any) => void;
}) {
  const config = normalizeFormFieldConfig(brick?.content?.formField);
  if (!config) {
    // Bricks without a `formField` config get a non-editable placeholder row.
    return (
      <View className="rounded-md border border-dashed border-border bg-background p-3">
        <Text className="text-xs text-muted-foreground">
          [bloque: {brick?.kind ?? '?'}]
        </Text>
      </View>
    );
  }

  return (
    <View>
      <View className="flex-row items-center justify-end gap-2 mb-1">
        {canMoveUp ? (
          <Pressable onPress={onMoveUp} hitSlop={6}>
            <ChevronUp size={14} color={colors.mutedForeground} />
          </Pressable>
        ) : null}
        {canMoveDown ? (
          <Pressable onPress={onMoveDown} hitSlop={6}>
            <ChevronDown size={14} color={colors.mutedForeground} />
          </Pressable>
        ) : null}
        <Pressable onPress={onDelete} hitSlop={6}>
          <Trash2 size={14} color={colors.destructive} />
        </Pressable>
      </View>
      <UnifiedFormFieldBrick
        id={brick.id}
        config={config}
        readonly={false}
        onUpdate={(nextConfig) =>
          onUpdate({
            ...(brick.content ?? {}),
            formField: nextConfig,
          })
        }
      />
    </View>
  );
}
